### PR TITLE
added macOS X display improvements

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by ffont** [comment]
Hey thanks for the PR!
Both the buttons are text styling are way better now, but I see two issues:

- In the previous version the last 3 songs that had been played were shown in the interface, one per line (note the `label_contents += ...` in https://github.com/ffont/BBC6Music/blob/master/BBC%206Music%20OSX/ViewController-OSX.swift#L76). With the current version only one is shown (multiline though).
- The only song that is shown is not in fact the last played as metadata items are iterated in reverse (https://github.com/ffont/BBC6Music/blob/master/BBC%206Music%20OSX/ViewController-OSX.swift#L69), therefore if I'm not wrong the interface will show the oldest item stored. In the previous interface this worked as I iterate them in reverse (newest first) and keep on appending them to `label_contents`. Now `label_contents` only has the last iterated song item, which corresponds to the oldest stored one.

I like the idea of seeing the N last played songs so I'll first merge this PR and then modify it to show more songs.

**Comment by gingerbeardman** [comment]
@ffont hey, I thought that you had planned for multiple entries being displayed. however, the endpoint you are calling - http://polling.bbc.co.uk/radio/realtime/bbc_6music.jsonp - only returns one item these days?

I have an [Alfred workflow/extension](https://www.alfredforum.com/topic/2194-whats-on-bbc-radio-6music/) that calls that endpoint so I was familar with it. My thing also takes into account the end time of the song so it will display "started X minute(s) ago" or "ended X minute(s) ago" if they are in between songs on the radio. This is easy by comparing their timestamps to time-from-1970/epoch.

**Comment by ffont** [comment]
Hi @gingerbeardman,

The endpoint only returns the last played item, but the metadata parser stores the last N distinct items returned after periodic calls to the endpoint, that's how it keeps "history".

The started vs ended thing would be a nice feature I agree.

**Comment by gingerbeardman** [comment]
Ah, nice! In that case there will be some issue with the way I have implemented bold track name.

**Comment by ffont** [comment]
yes, I fixed it in https://github.com/ffont/BBC6Music/commit/599af565a87e16311d4b6df44b95fd85d9480d13

**Comment by gingerbeardman** [comment]
Nice!

**Pull request merged**
